
# config.yaml
# Configuration file for the Acrobot environment

# Configuration for the environment
environment:
    total_time: 10.0
    speed_goal: 1.0


# Configuration for the feedback sampling
feedback_sampling:
    # sampling_exploration: [0.1, 0.3]
    # sampling_trajectories: 10
    # sampling_scale: 1.0
    # sampling_representation: 2
    # sampling_spline_points: 10
    # sampling_update_before_feedback: 3
    # sampling_cost_variance_threshold: 100.0
    # sampling_feedback_scale_gain: 1.0
    # sampling_improvement_value_gamma: 0.8

