# config.yaml
# Configuration file for the Acrobot environment

# Configuration for the environment
environment:
    total_time: 30.0

# Configuration for the feedback sampling
feedback_sampling:
    sampling_improvement_value_gamma: 0.8

